### ISSUE TITLE
Can you add a link to the Extension in the chrome store

### ISSUE THREAD

**Issue by jonniedarko** [doctolib/code-tours-github#193]
I think it would be helpful to add a link (this I believe https://chrome.google.com/webstore/detail/code-tours-github/emmipndjppboloecpfgnckbkcehhhpkc?hl=en) to the readme

**Comment by qmenoret** [comment]
Hello, thanks for raising the issue.
Actually, the images for Chrome and Firefox logos in the readme are links to the different store. Isn't that the one you're talking about?

**Comment by jonniedarko** [comment]
yes I guess so , it wasn't immediately clear that they were links, thanks

**Comment by qmenoret** [comment]
No worries! I'm closing this one then 🙂
