### ISSUE TITLE
This is the wrong repo but I don't see one for the website itself

### ISSUE THREAD

**Issue by AlexHarrowell** [doctolib/code-tours-github#49]
You should acquire appointments at the stage of confirming availability, and release the lock only if the last confirmation step is not completed within a reasonable timeout. At the moment, there exists a race condition where the web application tells the user their COVID-19 vaccination has been confirmed, and sends them to complete various click-through notices (too many). 

However, the appointments are still available to other users, so if the rate of arrival at the calendar page is greater than 1/(time taken to serve the confirmation pages), all bookings will invariably fail, as the appointment will be taken before the final confirmation step happens. The other user will then, with high probability, lose the appointment to the next one. (A symptom that this is the case - much earlier appointments constantly re-appear in the calendar as other users lose them)

Fix: use transactions, this is exactly why the 1950s airline reservation developers who invented the relational database invented them.

Further enhancement: you currently have three steps of confirmation post-availability check (clickthrough boxes, confirmation of various details, final confirmation) of which two require a page load. If the non-use of transactions is a scaling optimization you can take some of the scaling cost back by getting rid of at least two of these steps. This would also mean the timeout before the transaction expires could be shorter.

you should seriously look at the ratio of confirmed bookings to initiated bookings (i.e. what networking people call "goodput" vs throughput)

**Comment by qmenoret** [comment]
Hello,
This is not the repository of the Doctolib web app.
You can submit a bug report at doctolib.fr/tickets/new
I'm closing this issue.
